// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: access_control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthPolicyType int32

const (
	AuthPolicyType_NoneAuthPolicy AuthPolicyType = 0
	AuthPolicyType_UgiAuthPolicy  AuthPolicyType = 1
)

// Enum value maps for AuthPolicyType.
var (
	AuthPolicyType_name = map[int32]string{
		0: "NoneAuthPolicy",
		1: "UgiAuthPolicy",
	}
	AuthPolicyType_value = map[string]int32{
		"NoneAuthPolicy": 0,
		"UgiAuthPolicy":  1,
	}
)

func (x AuthPolicyType) Enum() *AuthPolicyType {
	p := new(AuthPolicyType)
	*p = x
	return p
}

func (x AuthPolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthPolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_access_control_proto_enumTypes[0].Descriptor()
}

func (AuthPolicyType) Type() protoreflect.EnumType {
	return &file_access_control_proto_enumTypes[0]
}

func (x AuthPolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthPolicyType.Descriptor instead.
func (AuthPolicyType) EnumDescriptor() ([]byte, []int) {
	return file_access_control_proto_rawDescGZIP(), []int{0}
}

// User-Group-Role-Permission 一个用户可以属于多个组，有多个Role
type IdentityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthPolicyType AuthPolicyType `protobuf:"varint,1,opt,name=auth_policy_type,json=authPolicyType,proto3,enum=bigtable.AuthPolicyType" json:"auth_policy_type,omitempty"`
	Name           string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Token          []byte         `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	IpAddr         string         `protobuf:"bytes,4,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"`
}

func (x *IdentityInfo) Reset() {
	*x = IdentityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_access_control_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdentityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityInfo) ProtoMessage() {}

func (x *IdentityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_access_control_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityInfo.ProtoReflect.Descriptor instead.
func (*IdentityInfo) Descriptor() ([]byte, []int) {
	return file_access_control_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityInfo) GetAuthPolicyType() AuthPolicyType {
	if x != nil {
		return x.AuthPolicyType
	}
	return AuthPolicyType_NoneAuthPolicy
}

func (x *IdentityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IdentityInfo) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *IdentityInfo) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

var File_access_control_proto protoreflect.FileDescriptor

var file_access_control_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x69, 0x67, 0x74, 0x61, 0x62, 0x6c, 0x65,
	0x22, 0x95, 0x01, 0x0a, 0x0c, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x42, 0x0a, 0x10, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x62, 0x69,
	0x67, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x17, 0x0a, 0x07, 0x69, 0x70, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x70, 0x41, 0x64, 0x64, 0x72, 0x2a, 0x37, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68,
	0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x6f,
	0x6e, 0x65, 0x41, 0x75, 0x74, 0x68, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x10, 0x00, 0x12, 0x11,
	0x0a, 0x0d, 0x55, 0x67, 0x69, 0x41, 0x75, 0x74, 0x68, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x10,
	0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x61, 0x6c, 0x6c, 0x65, 0x6e, 0x2d, 0x73, 0x68, 0x61, 0x77, 0x2f, 0x62, 0x69, 0x67, 0x74, 0x61,
	0x62, 0x6c, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_access_control_proto_rawDescOnce sync.Once
	file_access_control_proto_rawDescData = file_access_control_proto_rawDesc
)

func file_access_control_proto_rawDescGZIP() []byte {
	file_access_control_proto_rawDescOnce.Do(func() {
		file_access_control_proto_rawDescData = protoimpl.X.CompressGZIP(file_access_control_proto_rawDescData)
	})
	return file_access_control_proto_rawDescData
}

var file_access_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_access_control_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_access_control_proto_goTypes = []interface{}{
	(AuthPolicyType)(0),  // 0: bigtable.AuthPolicyType
	(*IdentityInfo)(nil), // 1: bigtable.IdentityInfo
}
var file_access_control_proto_depIdxs = []int32{
	0, // 0: bigtable.IdentityInfo.auth_policy_type:type_name -> bigtable.AuthPolicyType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_access_control_proto_init() }
func file_access_control_proto_init() {
	if File_access_control_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_access_control_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdentityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_access_control_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_access_control_proto_goTypes,
		DependencyIndexes: file_access_control_proto_depIdxs,
		EnumInfos:         file_access_control_proto_enumTypes,
		MessageInfos:      file_access_control_proto_msgTypes,
	}.Build()
	File_access_control_proto = out.File
	file_access_control_proto_rawDesc = nil
	file_access_control_proto_goTypes = nil
	file_access_control_proto_depIdxs = nil
}
