// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: status_code.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_OK StatusCode = 0
	// master status
	StatusCode_MasterNotInited   StatusCode = 12
	StatusCode_MasterIsBusy      StatusCode = 13
	StatusCode_MasterIsSecondary StatusCode = 14
	StatusCode_MasterIsReadonly  StatusCode = 15
	StatusCode_MasterOnRestore   StatusCode = 16
	StatusCode_MasterOnWait      StatusCode = 17
	StatusCode_MasterIsRunning   StatusCode = 19
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:  "OK",
		12: "MasterNotInited",
		13: "MasterIsBusy",
		14: "MasterIsSecondary",
		15: "MasterIsReadonly",
		16: "MasterOnRestore",
		17: "MasterOnWait",
		19: "MasterIsRunning",
	}
	StatusCode_value = map[string]int32{
		"OK":                0,
		"MasterNotInited":   12,
		"MasterIsBusy":      13,
		"MasterIsSecondary": 14,
		"MasterIsReadonly":  15,
		"MasterOnRestore":   16,
		"MasterOnWait":      17,
		"MasterIsRunning":   19,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_status_code_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_status_code_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{0}
}

type CompactStatus int32

const (
	CompactStatus_TabletUnknown   CompactStatus = 0
	CompactStatus_TableNotCompact CompactStatus = 1
	CompactStatus_TableOnCompact  CompactStatus = 2
	CompactStatus_TableCompacted  CompactStatus = 3
)

// Enum value maps for CompactStatus.
var (
	CompactStatus_name = map[int32]string{
		0: "TabletUnknown",
		1: "TableNotCompact",
		2: "TableOnCompact",
		3: "TableCompacted",
	}
	CompactStatus_value = map[string]int32{
		"TabletUnknown":   0,
		"TableNotCompact": 1,
		"TableOnCompact":  2,
		"TableCompacted":  3,
	}
)

func (x CompactStatus) Enum() *CompactStatus {
	p := new(CompactStatus)
	*p = x
	return p
}

func (x CompactStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CompactStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_status_code_proto_enumTypes[1].Descriptor()
}

func (CompactStatus) Type() protoreflect.EnumType {
	return &file_status_code_proto_enumTypes[1]
}

func (x CompactStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CompactStatus.Descriptor instead.
func (CompactStatus) EnumDescriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{1}
}

type TableStatus int32

const (
	TableStatus_TableUnknown  TableStatus = 0
	TableStatus_TableEnable   TableStatus = 1000
	TableStatus_TableDisable  TableStatus = 1001
	TableStatus_TableDeleting TableStatus = 1002
)

// Enum value maps for TableStatus.
var (
	TableStatus_name = map[int32]string{
		0:    "TableUnknown",
		1000: "TableEnable",
		1001: "TableDisable",
		1002: "TableDeleting",
	}
	TableStatus_value = map[string]int32{
		"TableUnknown":  0,
		"TableEnable":   1000,
		"TableDisable":  1001,
		"TableDeleting": 1002,
	}
)

func (x TableStatus) Enum() *TableStatus {
	p := new(TableStatus)
	*p = x
	return p
}

func (x TableStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_status_code_proto_enumTypes[2].Descriptor()
}

func (TableStatus) Type() protoreflect.EnumType {
	return &file_status_code_proto_enumTypes[2]
}

func (x TableStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableStatus.Descriptor instead.
func (TableStatus) EnumDescriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{2}
}

var File_status_code_proto protoreflect.FileDescriptor

var file_status_code_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62, 0x69, 0x67, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x2a, 0xa4, 0x01,
	0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02,
	0x4f, 0x4b, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4e, 0x6f,
	0x74, 0x49, 0x6e, 0x69, 0x74, 0x65, 0x64, 0x10, 0x0c, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x61, 0x73,
	0x74, 0x65, 0x72, 0x49, 0x73, 0x42, 0x75, 0x73, 0x79, 0x10, 0x0d, 0x12, 0x15, 0x0a, 0x11, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x73, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79,
	0x10, 0x0e, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x73, 0x52, 0x65,
	0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x10, 0x0f, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x4f, 0x6e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x10, 0x10, 0x12, 0x10, 0x0a,
	0x0c, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x6e, 0x57, 0x61, 0x69, 0x74, 0x10, 0x11, 0x12,
	0x13, 0x0a, 0x0f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x73, 0x52, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x10, 0x13, 0x2a, 0x5f, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x74, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x4e, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x10, 0x01, 0x12, 0x12, 0x0a,
	0x0e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x4f, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x10,
	0x02, 0x12, 0x12, 0x0a, 0x0e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63,
	0x74, 0x65, 0x64, 0x10, 0x03, 0x2a, 0x58, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x10, 0xe8, 0x07, 0x12, 0x11, 0x0a, 0x0c, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x10, 0xe9, 0x07, 0x12, 0x12, 0x0a, 0x0d, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x10, 0xea, 0x07, 0x42,
	0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c,
	0x6c, 0x65, 0x6e, 0x2d, 0x73, 0x68, 0x61, 0x77, 0x2f, 0x62, 0x69, 0x67, 0x74, 0x61, 0x62, 0x6c,
	0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_status_code_proto_rawDescOnce sync.Once
	file_status_code_proto_rawDescData = file_status_code_proto_rawDesc
)

func file_status_code_proto_rawDescGZIP() []byte {
	file_status_code_proto_rawDescOnce.Do(func() {
		file_status_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_status_code_proto_rawDescData)
	})
	return file_status_code_proto_rawDescData
}

var file_status_code_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_status_code_proto_goTypes = []interface{}{
	(StatusCode)(0),    // 0: bigtable.StatusCode
	(CompactStatus)(0), // 1: bigtable.CompactStatus
	(TableStatus)(0),   // 2: bigtable.TableStatus
}
var file_status_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_status_code_proto_init() }
func file_status_code_proto_init() {
	if File_status_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_status_code_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_status_code_proto_goTypes,
		DependencyIndexes: file_status_code_proto_depIdxs,
		EnumInfos:         file_status_code_proto_enumTypes,
	}.Build()
	File_status_code_proto = out.File
	file_status_code_proto_rawDesc = nil
	file_status_code_proto_goTypes = nil
	file_status_code_proto_depIdxs = nil
}
